In [ ]:
pip install beautifulsoup4   #for webscrapping

In [ ]:
pip install gensim   #word2vec library

In [ ]:
#Scrapping the data from the website 

In [ ]:
import bs4 as bs
import urllib.request 
import requests


In [ ]:
scrap_data = urllib.request.urlopen('https://en.wikipedia.org/wiki/Deep_learning')   #to load data

In [ ]:
article = scrap_data.read()

In [ ]:
parsed_article = bs.BeautifulSoup(article)   #to convert into a form that is understandable

In [ ]:
parsed_article

<!DOCTYPE html>
<html class="client-nojs" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>Deep learning - Wikipedia</title>
<script>document.documentElement.className="client-js";RLCONF={"wgBreakFrames":!1,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"675dfe9a-c2ff-4dba-b63f-d8f824e9a4ea","wgCSPNonce":!1,"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":!1,"wgNamespaceNumber":0,"wgPageName":"Deep_learning","wgTitle":"Deep learning","wgCurRevisionId":1024861233,"wgRevisionId":1024861233,"wgArticleId":32472154,"wgIsArticle":!0,"wgIsRedirect":!1,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Webarchive template wayback links","CS1: long volume value","CS1 errors: missing periodical","CS1 maint: archived copy as title","Articles with short description","Sh

In [ ]:
parsed_article.title.string

'Deep learning - Wikipedia'

In [ ]:
parsed_article.p   #gives only one paragraph

<p><b>Deep learning</b>  (also known as <b>deep structured learning</b>) is part of a broader family of <a href="/wiki/Machine_learning" title="Machine learning">machine learning</a> methods based on <a class="mw-redirect" href="/wiki/Artificial_neural_networks" title="Artificial neural networks">artificial neural networks</a> with <a class="mw-redirect" href="/wiki/Representation_learning" title="Representation learning">representation learning</a>. Learning can be <a href="/wiki/Supervised_learning" title="Supervised learning">supervised</a>, <a href="/wiki/Semi-supervised_learning" title="Semi-supervised learning">semi-supervised</a> or <a href="/wiki/Unsupervised_learning" title="Unsupervised learning">unsupervised</a>.<sup class="reference" id="cite_ref-BENGIO2012_1-0"><a href="#cite_note-BENGIO2012-1">[1]</a></sup><sup class="reference" id="cite_ref-SCHIDHUB_2-0"><a href="#cite_note-SCHIDHUB-2">[2]</a></sup><sup class="reference" id="cite_ref-NatureBengio_3-0"><a href="#cite_note

In [ ]:
paragraph = parsed_article.find_all('p')   #to get all the paragraphs and it only searches for html syntax p and not words

In [ ]:
paragraph

[<p><b>Deep learning</b>  (also known as <b>deep structured learning</b>) is part of a broader family of <a href="/wiki/Machine_learning" title="Machine learning">machine learning</a> methods based on <a class="mw-redirect" href="/wiki/Artificial_neural_networks" title="Artificial neural networks">artificial neural networks</a> with <a class="mw-redirect" href="/wiki/Representation_learning" title="Representation learning">representation learning</a>. Learning can be <a href="/wiki/Supervised_learning" title="Supervised learning">supervised</a>, <a href="/wiki/Semi-supervised_learning" title="Semi-supervised learning">semi-supervised</a> or <a href="/wiki/Unsupervised_learning" title="Unsupervised learning">unsupervised</a>.<sup class="reference" id="cite_ref-BENGIO2012_1-0"><a href="#cite_note-BENGIO2012-1">[1]</a></sup><sup class="reference" id="cite_ref-SCHIDHUB_2-0"><a href="#cite_note-SCHIDHUB-2">[2]</a></sup><sup class="reference" id="cite_ref-NatureBengio_3-0"><a href="#cite_not

In [ ]:
for p in paragraph:
  print(p.text)

Deep learning  (also known as deep structured learning) is part of a broader family of machine learning methods based on artificial neural networks with representation learning. Learning can be supervised, semi-supervised or unsupervised.[1][2][3]

Deep-learning architectures such as deep neural networks, deep belief networks, graph neural networks, recurrent neural networks and convolutional neural networks have been applied to fields including computer vision, speech recognition, natural language processing, machine translation, bioinformatics, drug design, medical image analysis, material inspection and board game programs, where they have produced results comparable to and in some cases surpassing human expert performance.[4][5][6][7]

Artificial neural networks (ANNs) were inspired by information processing and distributed communication nodes in biological systems. ANNs have various differences from biological brains.  Specifically, neural networks tend to be static and symbolic, 

In [ ]:
article_text = ''
for p in paragraph:
  article_text = article_text + p.text

In [ ]:
article_text

'Deep learning  (also known as deep structured learning) is part of a broader family of machine learning methods based on artificial neural networks with representation learning. Learning can be supervised, semi-supervised or unsupervised.[1][2][3]\nDeep-learning architectures such as deep neural networks, deep belief networks, graph neural networks, recurrent neural networks and convolutional neural networks have been applied to fields including computer vision, speech recognition, natural language processing, machine translation, bioinformatics, drug design, medical image analysis, material inspection and board game programs, where they have produced results comparable to and in some cases surpassing human expert performance.[4][5][6][7]\nArtificial neural networks (ANNs) were inspired by information processing and distributed communication nodes in biological systems. ANNs have various differences from biological brains.  Specifically, neural networks tend to be static and symbolic,

In [ ]:
len(article_text)

45007

In [ ]:
#Data cleaning

In [ ]:
import nltk
nltk.download('punkt')   #this is imported after running and to resolve the error
from nltk.corpus import stopwords
nltk.download('stopwords')
stop = stopwords.words('english')

import re
import pandas as pd
import numpy as np


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
processed_article = article_text.lower()

In [ ]:
processed_article

'deep learning  (also known as deep structured learning) is part of a broader family of machine learning methods based on artificial neural networks with representation learning. learning can be supervised, semi-supervised or unsupervised.[1][2][3]\ndeep-learning architectures such as deep neural networks, deep belief networks, graph neural networks, recurrent neural networks and convolutional neural networks have been applied to fields including computer vision, speech recognition, natural language processing, machine translation, bioinformatics, drug design, medical image analysis, material inspection and board game programs, where they have produced results comparable to and in some cases surpassing human expert performance.[4][5][6][7]\nartificial neural networks (anns) were inspired by information processing and distributed communication nodes in biological systems. anns have various differences from biological brains.  specifically, neural networks tend to be static and symbolic,

In [ ]:
processed_article = re.sub('[^a-z]',' ',processed_article)

In [ ]:
processed_article

'deep learning   also known as deep structured learning  is part of a broader family of machine learning methods based on artificial neural networks with representation learning  learning can be supervised  semi supervised or unsupervised           deep learning architectures such as deep neural networks  deep belief networks  graph neural networks  recurrent neural networks and convolutional neural networks have been applied to fields including computer vision  speech recognition  natural language processing  machine translation  bioinformatics  drug design  medical image analysis  material inspection and board game programs  where they have produced results comparable to and in some cases surpassing human expert performance              artificial neural networks  anns  were inspired by information processing and distributed communication nodes in biological systems  anns have various differences from biological brains   specifically  neural networks tend to be static and symbolic  w

In [ ]:
all_sentence = nltk.sent_tokenize(processed_article)

In [ ]:
all_words = nltk.word_tokenize(processed_article)

In [ ]:
all_words_1 = [nltk.word_tokenize(sent)for sent in all_sentence]

In [ ]:
len(all_words_1)

1

In [ ]:
clean_text = [w for w in all_words_1 if w not in stop]

In [ ]:
clean_text

[['deep',
  'learning',
  'also',
  'known',
  'as',
  'deep',
  'structured',
  'learning',
  'is',
  'part',
  'of',
  'a',
  'broader',
  'family',
  'of',
  'machine',
  'learning',
  'methods',
  'based',
  'on',
  'artificial',
  'neural',
  'networks',
  'with',
  'representation',
  'learning',
  'learning',
  'can',
  'be',
  'supervised',
  'semi',
  'supervised',
  'or',
  'unsupervised',
  'deep',
  'learning',
  'architectures',
  'such',
  'as',
  'deep',
  'neural',
  'networks',
  'deep',
  'belief',
  'networks',
  'graph',
  'neural',
  'networks',
  'recurrent',
  'neural',
  'networks',
  'and',
  'convolutional',
  'neural',
  'networks',
  'have',
  'been',
  'applied',
  'to',
  'fields',
  'including',
  'computer',
  'vision',
  'speech',
  'recognition',
  'natural',
  'language',
  'processing',
  'machine',
  'translation',
  'bioinformatics',
  'drug',
  'design',
  'medical',
  'image',
  'analysis',
  'material',
  'inspection',
  'and',
  'board',
  'gam

In [ ]:
len(clean_text)

1

In [ ]:
#Implementing word2vec

In [ ]:
from gensim.models import Word2Vec

In [ ]:
window_length = 3
embedding_dimension = 300
min_count = 1
no_of_cores = 4
epoch = 10
skipgram = 1  

In [ ]:
word2vec_1 = Word2Vec(clean_text,size = embedding_dimension,window=window_length,min_count=min_count,workers=no_of_cores,iter=epoch,sg=skipgram)

In [ ]:
vocabulary = word2vec_1.wv.vectors

In [ ]:
vocabulary

array([[-0.09425261,  0.01591326,  0.06084138, ..., -0.09292089,
        -0.07277589, -0.07601707],
       [-0.09346823,  0.01405124,  0.0614094 , ..., -0.09110726,
        -0.06972124, -0.07372783],
       [-0.09688499,  0.01424076,  0.06082958, ..., -0.09538899,
        -0.07235506, -0.07775249],
       ...,
       [-0.01730422,  0.00324884,  0.01056278, ..., -0.01753878,
        -0.0158839 , -0.0131861 ],
       [-0.01842243,  0.00463276,  0.01293915, ..., -0.0189971 ,
        -0.01453737, -0.01689657],
       [-0.01668411,  0.00260959,  0.01097378, ..., -0.01645616,
        -0.01196903, -0.01315243]], dtype=float32)

In [ ]:
word2vec_1.wv['learning']

array([-8.01250264e-02,  1.55149456e-02,  5.44992276e-02, -7.48141259e-02,
       -3.30124609e-02,  4.07562926e-02, -8.86816904e-02, -8.62025917e-02,
       -8.16506296e-02,  1.28704816e-01, -3.40382718e-02, -2.32897867e-02,
       -5.55177368e-02,  1.00614473e-01, -9.48836133e-02,  2.78527681e-02,
       -5.29898293e-02,  1.75965205e-02, -3.54741863e-03,  7.36972541e-02,
       -4.08336939e-03, -7.42345899e-02, -8.72656032e-02, -4.69320677e-02,
       -3.60731175e-03, -1.34990886e-01, -9.74262059e-02, -1.15867354e-01,
        5.13943322e-02, -7.21155554e-02, -8.22606981e-02, -5.61871417e-02,
       -1.02019779e-01,  1.70846954e-02,  7.99906701e-02,  1.63394049e-01,
        8.05875845e-03,  2.11891886e-02, -7.54097924e-02, -4.54625823e-02,
        8.65023881e-02,  1.99013799e-01, -5.89019954e-02,  2.32837237e-02,
       -9.80330072e-03,  5.18687703e-02,  7.56433681e-02, -6.07980490e-02,
       -1.80260073e-02,  5.68827391e-02,  1.60112965e-03,  2.21424028e-01,
        9.76751596e-02,  

In [ ]:
similar_words = word2vec_1.most_similar('learning',topn = 5)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


In [ ]:
similar_words

[('and', 0.9998122453689575),
 ('most', 0.9998080730438232),
 ('or', 0.999799370765686),
 ('these', 0.9997985363006592),
 ('that', 0.9997978210449219)]

In [ ]:
word2vec_1.most_similar(positive=['deep','neural'],negative=['learning'],topn=3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


[('the', 0.9995098114013672),
 ('by', 0.9995097517967224),
 ('were', 0.999504804611206)]

In [ ]:
word2vec_1.save('skipgram.bin')

In [ ]:
skipgram_model = Word2Vec.load('skipgram.bin')

In [ ]:
skipgram_model.wv['learning']

array([-8.01250264e-02,  1.55149456e-02,  5.44992276e-02, -7.48141259e-02,
       -3.30124609e-02,  4.07562926e-02, -8.86816904e-02, -8.62025917e-02,
       -8.16506296e-02,  1.28704816e-01, -3.40382718e-02, -2.32897867e-02,
       -5.55177368e-02,  1.00614473e-01, -9.48836133e-02,  2.78527681e-02,
       -5.29898293e-02,  1.75965205e-02, -3.54741863e-03,  7.36972541e-02,
       -4.08336939e-03, -7.42345899e-02, -8.72656032e-02, -4.69320677e-02,
       -3.60731175e-03, -1.34990886e-01, -9.74262059e-02, -1.15867354e-01,
        5.13943322e-02, -7.21155554e-02, -8.22606981e-02, -5.61871417e-02,
       -1.02019779e-01,  1.70846954e-02,  7.99906701e-02,  1.63394049e-01,
        8.05875845e-03,  2.11891886e-02, -7.54097924e-02, -4.54625823e-02,
        8.65023881e-02,  1.99013799e-01, -5.89019954e-02,  2.32837237e-02,
       -9.80330072e-03,  5.18687703e-02,  7.56433681e-02, -6.07980490e-02,
       -1.80260073e-02,  5.68827391e-02,  1.60112965e-03,  2.21424028e-01,
        9.76751596e-02,  